export type BetaProjectStatus =
  | "draft"
  | "breaking_down"
  | "product_pending"
  | "script_generating"
  | "script_pending"
  | "rendering"
  | "completed"
  | "failed"

export interface BetaProject {
  id: string
  title: string
  source: string
  product: string
  status: BetaProjectStatus
  createdAt: string
  updatedAt: string
  cover: string
}

export interface BetaMaterial {
  id: string
  title: string
  account: string
  source: string
  cover: string
  video: string
  duration: string
  evidence: string
  updatedAt: string
}

export const BETA_VIDEO = "/creative-assets/wedding-dress-ad.mp4"

export const BETA_MATERIALS: BetaMaterial[] = [
  {
    id: "aigc-003",
    title: "力量感开场：运动内衣承托测试",
    account: "@motion.lab",
    source: "AIGC 爆款",
    cover: "/replicate-covers/sports-bra.jpg",
    video: BETA_VIDEO,
    duration: "00:20",
    evidence: "约 $3万+ GMV · 145万+ 播放",
    updatedAt: "2026-06-21",
  },
  {
    id: "aigc-004",
    title: "三步完成通透底妆",
    account: "@beauty.minute",
    source: "AIGC 爆款",
    cover: "/replicate-covers/beauty-makeup.jpg",
    video: BETA_VIDEO,
    duration: "00:15",
    evidence: "约 $7.6万+ GMV · 238万+ 播放",
    updatedAt: "2026-06-20",
  },
  {
    id: "market-001",
    title: "一秒换装：多场景机能短裤展示",
    account: "@urban.motion",
    source: "市场爆款",
    cover: "/replicate-covers/cargo-shorts.jpg",
    video: BETA_VIDEO,
    duration: "00:09",
    evidence: "112万+ 播放 · 8.6万点赞",
    updatedAt: "2026-06-22",
  },
  {
    id: "brand-001",
    title: "镜前试穿：针织开衫真实反馈",
    account: "@atelier.daily",
    source: "品牌追踪",
    cover: "/replicate-covers/knit-cardigan.jpg",
    video: BETA_VIDEO,
    duration: "00:10",
    evidence: "连续投放 18 天 · 168万+ 播放",
    updatedAt: "2026-06-22",
  },
]

export const BETA_PROJECTS: BetaProject[] = [
  {
    id: "beta-completed",
    title: "运动内衣承托测试 · 美国站",
    source: "AIGC 爆款",
    product: "FlexForm 高支撑运动内衣",
    status: "completed",
    createdAt: "2026-07-24",
    updatedAt: "12 分钟前",
    cover: BETA_MATERIALS[0].cover,
  },
  {
    id: "beta-script",
    title: "通透底妆三步教程 · v2",
    source: "AIGC 爆款",
    product: "LumaSkin 轻透粉底液",
    status: "script_pending",
    createdAt: "2026-07-23",
    updatedAt: "昨天 18:42",
    cover: BETA_MATERIALS[1].cover,
  },
  {
    id: "beta-product",
    title: "机能短裤一秒换装",
    source: "市场爆款",
    product: "UrbanArc 工装短裤",
    status: "product_pending",
    createdAt: "2026-07-23",
    updatedAt: "昨天 15:10",
    cover: BETA_MATERIALS[2].cover,
  },
  {
    id: "beta-breaking",
    title: "针织开衫镜前试穿",
    source: "品牌追踪",
    product: "待确认",
    status: "breaking_down",
    createdAt: "2026-07-22",
    updatedAt: "2 天前",
    cover: BETA_MATERIALS[3].cover,
  },
  {
    id: "beta-failed",
    title: "便携榨汁杯痛点演示",
    source: "本地上传",
    product: "MixGo 便携榨汁杯",
    status: "failed",
    createdAt: "2026-07-21",
    updatedAt: "3 天前",
    cover: "/replicate-covers/portable-blender.jpg",
  },
  {
    id: "beta-draft",
    title: "未命名复刻项目",
    source: "未选择",
    product: "待确认",
    status: "draft",
    createdAt: "2026-07-19",
    updatedAt: "5 天前",
    cover: "/replicate-covers/creative-draft.jpg",
  },
  {
    id: "beta-rendering-shapewear",
    title: "无痕塑形衣侧身对比",
    source: "AIGC 爆款",
    product: "ShapeEase 无痕塑形衣",
    status: "rendering",
    createdAt: "2026-07-18",
    updatedAt: "6 天前",
    cover: "/replicate-covers/sports-bra.jpg",
  },
  {
    id: "beta-draft-skincare",
    title: "精华液吸收速度测试",
    source: "本地上传",
    product: "待确认",
    status: "draft",
    createdAt: "2026-07-18",
    updatedAt: "6 天前",
    cover: "/replicate-covers/beauty-makeup.jpg",
  },
  {
    id: "beta-product-coffee",
    title: "冷萃咖啡晨间场景",
    source: "市场爆款",
    product: "BrewDay 冷萃咖啡液",
    status: "product_pending",
    createdAt: "2026-07-17",
    updatedAt: "7 天前",
    cover: "/replicate-covers/portable-blender.jpg",
  },
  {
    id: "beta-breaking-jewelry",
    title: "通勤首饰一周搭配",
    source: "品牌追踪",
    product: "待确认",
    status: "breaking_down",
    createdAt: "2026-07-17",
    updatedAt: "7 天前",
    cover: "/replicate-covers/knit-cardigan.jpg",
  },
  {
    id: "beta-script-pet",
    title: "宠物除毛刷效果证明",
    source: "AIGC 爆款",
    product: "CleanPaw 宠物除毛刷",
    status: "script_pending",
    createdAt: "2026-07-16",
    updatedAt: "8 天前",
    cover: "/replicate-covers/creative-draft.jpg",
  },
  {
    id: "beta-completed-shoes",
    title: "轻量跑鞋弯折测试",
    source: "市场爆款",
    product: "RunAir 轻量跑鞋",
    status: "completed",
    createdAt: "2026-07-16",
    updatedAt: "8 天前",
    cover: "/replicate-covers/cargo-shorts.jpg",
  },
  {
    id: "beta-failed-lamp",
    title: "磁吸氛围灯安装演示",
    source: "本地上传",
    product: "GlowBar 磁吸氛围灯",
    status: "failed",
    createdAt: "2026-07-15",
    updatedAt: "9 天前",
    cover: "/replicate-covers/creative-draft.jpg",
  },
  {
    id: "beta-rendering-bottle",
    title: "保温杯十二小时温度测试",
    source: "品牌追踪",
    product: "ThermoGo 保温杯",
    status: "rendering",
    createdAt: "2026-07-15",
    updatedAt: "9 天前",
    cover: "/replicate-covers/portable-blender.jpg",
  },
  {
    id: "beta-draft-luggage",
    title: "登机箱容量挑战",
    source: "未选择",
    product: "待确认",
    status: "draft",
    createdAt: "2026-07-14",
    updatedAt: "10 天前",
    cover: "/replicate-covers/cargo-shorts.jpg",
  },
  {
    id: "beta-product-snack",
    title: "低卡脆片办公室试吃",
    source: "AIGC 爆款",
    product: "CrispyDay 低卡脆片",
    status: "product_pending",
    createdAt: "2026-07-14",
    updatedAt: "10 天前",
    cover: "/replicate-covers/beauty-makeup.jpg",
  },
  {
    id: "beta-breaking-earbuds",
    title: "降噪耳机地铁实测",
    source: "市场爆款",
    product: "待确认",
    status: "breaking_down",
    createdAt: "2026-07-13",
    updatedAt: "11 天前",
    cover: "/replicate-covers/creative-draft.jpg",
  },
  {
    id: "beta-script-yoga",
    title: "瑜伽裤深蹲不透测试",
    source: "品牌追踪",
    product: "MoveFree 高弹瑜伽裤",
    status: "script_pending",
    createdAt: "2026-07-13",
    updatedAt: "11 天前",
    cover: "/replicate-covers/sports-bra.jpg",
  },
  {
    id: "beta-completed-serum",
    title: "夜间修护精华七日记录",
    source: "AIGC 爆款",
    product: "NightLab 修护精华",
    status: "completed",
    createdAt: "2026-07-12",
    updatedAt: "12 天前",
    cover: "/replicate-covers/beauty-makeup.jpg",
  },
  {
    id: "beta-rendering-dress",
    title: "通勤连衣裙三种场景",
    source: "市场爆款",
    product: "MoriDay 通勤连衣裙",
    status: "rendering",
    createdAt: "2026-07-12",
    updatedAt: "12 天前",
    cover: "/replicate-covers/knit-cardigan.jpg",
  },
  {
    id: "beta-draft-cleaner",
    title: "桌面清洁器碎屑挑战",
    source: "本地上传",
    product: "待确认",
    status: "draft",
    createdAt: "2026-07-11",
    updatedAt: "13 天前",
    cover: "/replicate-covers/portable-blender.jpg",
  },
]

export const STATUS_META: Record<BetaProjectStatus, { label: string; tone: string }> = {
  draft: { label: "草稿", tone: "#71717a" },
  breaking_down: { label: "拆解完成", tone: "#2563eb" },
  product_pending: { label: "商品待确认", tone: "#d97706" },
  script_generating: { label: "脚本生成中", tone: "#7c3aed" },
  script_pending: { label: "脚本待确认", tone: "#7c3aed" },
  rendering: { label: "生成中", tone: "#0284c7" },
  completed: { label: "已完成", tone: "#15803d" },
  failed: { label: "失败，可重试", tone: "#dc2626" },
}

export const BREAKDOWN_SCENES = [
  { id: "s1", role: "Hook", time: "00:00-00:03", title: "力量动作直入主题", detail: "中近景人物拉伸肩背，第一秒建立力量感，并快速亮出产品轮廓。" },
  { id: "s2", role: "Body", time: "00:03-00:09", title: "结构与穿着演示", detail: "正面、侧面连续切镜，展示肩带、下围和包裹结构。" },
  { id: "s3", role: "Proof", time: "00:09-00:16", title: "承托效果证明", detail: "跳跃和伸展动作验证稳定性，近景补充面料弹性。" },
  { id: "s4", role: "CTA", time: "00:16-00:20", title: "核心利益点收束", detail: "定格产品与人物状态，用一句短口播强化全天舒适与稳定承托。" },
]

export const SCRIPT_BRIEF = {
  overallStrategy: "沿用参考视频“痛点拉停—结构认知—场景代入—动态实测—利益证明—行动收束”的高转化骨架，把每个阶段改写为 FlexForm 高支撑运动内衣的真实卖点与可执行镜头。",
  targetAudience: "进行跑步、跳操和力量训练，重视稳定承托但不愿牺牲舒适度的女性用户。",
  userProblem: "运动中肩带移位、胸部晃动和下围勒感会打断训练节奏，让用户需要反复整理内衣。",
  corePromise: "通过加宽肩带、包裹式下围和高弹面料，让中高强度动作保持稳定、贴合且活动自由。",
  useScenarios: ["跑步训练", "跳操 / HIIT", "力量训练", "日常高强度活动"],
  emotionalJourney: ["痛点共鸣", "结构理解", "场景代入", "实测验证", "安心确认", "行动决策"],
}

export const SCRIPT_SCENES = [
  {
    id: "script-1",
    time: "0-3s",
    role: "hook",
    duration: 3,
    functionBrief: "以运动痛点提问快速抓住注意力",
    strategy: "用肩带滑落的真实困扰建立共鸣，并在前三秒抛出承托测试悬念。",
    description: "先让用户看见肩带移位，再快速亮出完整产品状态，形成问题与解决方案的首轮对照。",
    adaptationLogic: "保留原片首秒直入动作和短问句节奏；将泛化力量展示改为更具体的肩带移位痛点。",
    keyMessages: ["肩带频繁移位", "承托测试"],
    shots: [
      {
        id: "shot-1",
        time: "0-1.2s",
        duration: 1.2,
        speaker: "新人物模特",
        shotSize: "肩部特写",
        cameraMovement: "手持快速推近",
        action: "模特完成一次开合跳后抬手拉回滑动的肩带，表情略显无奈。",
        visual: "镜头贴近肩颈与肩带位置，先看到肩带移位，再在动作结束点定格半拍。",
        voiceover: "Still fixing your straps mid-workout?",
        voiceoverTranslation: "运动到一半，还在反复整理肩带？",
        subtitle: "STRAPS SLIPPING AGAIN?",
        editingNote: "首帧直接给问题动作，0.4 秒处配合肩带回拉加入轻微冲击音。",
      },
      {
        id: "shot-2",
        time: "1.2-3s",
        duration: 1.8,
        speaker: "新人物模特",
        shotSize: "中近景",
        cameraMovement: "快速拉远后稳定跟拍",
        action: "模特换上 FlexForm 面向镜头抬臂，随后进入准备起跳姿势。",
        visual: "完整露出加宽肩带与包裹式下围，画面右侧弹出 Support test 测试标签。",
        voiceover: "Let’s see what real support looks like.",
        voiceoverTranslation: "现在看看，真正的稳定承托是什么样。",
        subtitle: "REAL SUPPORT TEST",
        editingNote: "用动作匹配切镜完成前后对照，结尾卡在起跳前制造继续观看的悬念。",
      },
    ],
  },
  {
    id: "script-2",
    time: "3-7s",
    role: "product_features",
    duration: 4,
    functionBrief: "聚焦结构卖点建立产品认知",
    strategy: "通过正侧面连续切换与手势指引，把加宽肩带和包裹式下围转化为直观看得懂的结构优势。",
    description: "用两组结构特写回答为什么更稳：上半段解释肩部受力，下半段解释下围包裹。",
    adaptationLogic: "保留参考视频连续展示产品结构的段落功能，将单一展示拆成肩带与下围两条独立证据。",
    keyMessages: ["加宽肩带", "包裹式下围", "分散压力"],
    shots: [
      {
        id: "shot-3",
        time: "3-5s",
        duration: 2,
        speaker: "新人物模特",
        shotSize: "肩带微距特写",
        cameraMovement: "横向缓慢滑动",
        action: "模特用两指轻压肩带展示宽度与回弹，手臂同步完成上举。",
        visual: "肩带受力面积以细线标注，画面保留皮肤接触处，证明压力被摊开。",
        voiceover: "Wide straps spread pressure across your shoulders.",
        voiceoverTranslation: "加宽肩带把压力均匀分散在肩部。",
        subtitle: "WIDE STRAPS · LESS PRESSURE",
        editingNote: "字幕跟随肩带轮廓出现，不遮挡产品边缘。",
      },
      {
        id: "shot-4",
        time: "5-7s",
        duration: 2,
        speaker: "新人物模特",
        shotSize: "侧腰近景",
        cameraMovement: "由侧面弧形移动至正面",
        action: "模特转身并轻拉下围，随后松手展示快速回弹和贴合。",
        visual: "镜头沿包裹式下围移动，重点显示侧翼宽度、贴合边缘与无卷边状态。",
        voiceover: "The wraparound band stays flat and locks in support.",
        voiceoverTranslation: "包裹式下围平整贴合，把承托稳稳锁住。",
        subtitle: "FLAT · SECURE · NO ROLLING",
        editingNote: "在松手回弹点加入短促节拍，完成结构段落收束。",
      },
    ],
  },
  {
    id: "script-3",
    time: "7-9.5s",
    role: "scenario_application",
    duration: 2.5,
    functionBrief: "快速覆盖三类高频训练场景",
    strategy: "用同一人物、同一机位的动作匹配切镜，让用户快速确认产品适用于自己的训练组合。",
    description: "跑步机、跳绳与哑铃深蹲三个场景连续衔接，强化并非只适合低强度动作的认知。",
    adaptationLogic: "继承参考视频的多场景覆盖功能，但用统一构图和动作匹配控制节奏。",
    keyMessages: ["跑步", "跳操", "力量训练"],
    shots: [
      {
        id: "shot-5",
        time: "7-9.5s",
        duration: 2.5,
        speaker: "新人物模特",
        shotSize: "三组中景快切",
        cameraMovement: "固定机位动作匹配切镜",
        action: "模特依次跑步、跳绳、完成哑铃深蹲，每个动作保留一个完整发力节拍。",
        visual: "三场景保持人物居中与相似光位，左下角依次出现 RUN / JUMP / LIFT。",
        voiceover: "Run, jump, lift—without stopping to readjust.",
        voiceoverTranslation: "跑步、跳跃、力量训练，都不用停下来反复整理。",
        subtitle: "RUN · JUMP · LIFT",
        editingNote: "三个动作按 0.8 秒节拍硬切，利用肢体位置匹配保证连续性。",
      },
    ],
  },
  {
    id: "script-4",
    time: "9.5-15s",
    role: "product_demo",
    duration: 5.5,
    functionBrief: "用连续动态测试建立可信证据",
    strategy: "先用正面跳跃验证纵向稳定，再用侧面伸展验证活动自由，形成承托与舒适的双重证明。",
    description: "测试镜头保留动作前后产品位置与身体状态，降低广告感并增强可信度。",
    adaptationLogic: "保留原片动作证明方法，将单一展示升级为正面稳定测试与侧面延展测试。",
    keyMessages: ["稳定承托", "不移位", "活动自由"],
    shots: [
      {
        id: "shot-6",
        time: "9.5-12.5s",
        duration: 3,
        speaker: "新人物模特",
        shotSize: "正面全身景转胸部近景",
        cameraMovement: "稳定器轻跟随，落地后快速推近",
        action: "模特连续完成三次开合跳，落地后双手自然垂下，不整理肩带或下围。",
        visual: "前两次保留全身动作，第三次落地切近景，对比产品位置保持不变。",
        voiceover: "Three jumps. No slipping, no digging, no reset.",
        voiceoverTranslation: "连续三次跳跃，不滑、不勒，也不用重新调整。",
        subtitle: "NO SLIP · NO DIG · NO RESET",
        editingNote: "三次落地各配一个节拍点，第三次用轻微放大强化测试结果。",
      },
      {
        id: "shot-7",
        time: "12.5-15s",
        duration: 2.5,
        speaker: "新人物模特",
        shotSize: "侧面中近景",
        cameraMovement: "低速侧向跟拍",
        action: "模特完成过顶拉伸与躯干旋转，面料随动作延展后恢复贴合。",
        visual: "侧面显示腋下、背部与下围没有卷起，画面以细线提示四向弹力。",
        voiceover: "Four-way stretch moves with you, then snaps right back.",
        voiceoverTranslation: "四向高弹跟随身体伸展，动作结束马上恢复贴合。",
        subtitle: "4-WAY STRETCH",
        editingNote: "用一次慢放突出面料延展，动作结束恢复正常速度。",
      },
    ],
  },
  {
    id: "script-5",
    time: "15-17.5s",
    role: "benefit_highlight",
    duration: 2.5,
    functionBrief: "把结构和测试转化为用户可感知的结果",
    strategy: "测试完成后不再堆叠新卖点，用自然呼吸和放松状态总结稳定但不束缚的核心收益。",
    description: "模特结束训练后自然呼吸并抬臂检查贴合状态，人物情绪由专注转为轻松。",
    adaptationLogic: "保留参考视频测试后的结果确认，用人物状态替代纯文字宣称。",
    keyMessages: ["稳定不束缚", "训练更专注", "舒适贴合"],
    shots: [
      {
        id: "shot-8",
        time: "15-17.5s",
        duration: 2.5,
        speaker: "新人物模特",
        shotSize: "中近景",
        cameraMovement: "缓慢推近",
        action: "模特训练结束后深呼吸并自然抬臂，轻松微笑，产品保持原位。",
        visual: "画面左右依次出现 Locked-in support 和 Freedom to move，最终合并为主利益点。",
        voiceover: "Locked-in support, without feeling locked in.",
        voiceoverTranslation: "承托稳稳锁住，身体却依然自由。",
        subtitle: "SECURE SUPPORT · FREE MOVEMENT",
        editingNote: "音乐由强节拍转为舒展长音，给 CTA 留出情绪落点。",
      },
    ],
  },
  {
    id: "script-6",
    time: "17.5-20s",
    role: "cta",
    duration: 2.5,
    functionBrief: "以品牌与核心利益点完成收束",
    strategy: "在动作结束后的稳定状态中露出品牌名，用短行动号召把注意力从反复调整转向专注训练。",
    description: "保留人物与产品同框，品牌、品名和行动按钮按层级依次出现。",
    adaptationLogic: "沿用参考视频短句收尾和产品定格，将泛化口号改为对开场痛点的闭环回应。",
    keyMessages: ["FlexForm", "专注训练", "高支撑运动内衣"],
    shots: [
      {
        id: "shot-9",
        time: "17.5-20s",
        duration: 2.5,
        speaker: "新人物模特",
        shotSize: "产品与人物中景",
        cameraMovement: "固定机位，结尾轻推近",
        action: "模特拿起外套搭在肩上面向镜头，保持自然站姿并轻点产品肩带。",
        visual: "FlexForm 品牌名、High-Support Sports Bra 品名与 Shop now 按钮依次进入安全区。",
        voiceover: "Choose FlexForm. Focus on the workout—not the fit.",
        voiceoverTranslation: "选择 FlexForm，把注意力留给训练，而不是反复调整。",
        subtitle: "FLEXFORM · MOVE WITHOUT DISTRACTION",
        editingNote: "品牌露出至少保留 1.5 秒，按钮在最后 0.8 秒出现。",
      },
    ],
  },
]